import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
import calendar

# Page configuration
st.set_page_config(
    page_title="Production Analytics Dashboard",
    page_icon="📊",
    layout="wide"
)

# Custom CSS
st.markdown("""
    <style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #1f77b4;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-size: 1.1rem;
        color: #666;
        margin-bottom: 2rem;
    }
    </style>
""", unsafe_allow_html=True)

# Header
st.markdown('<div class="main-header">📊 Production Analytics Dashboard</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Upload your production report to view interactive analytics</div>', unsafe_allow_html=True)
st.markdown("---")

# File upload in main area
st.markdown("### 📁 Upload Production Report")
uploaded_file = st.file_uploader(
    "Choose your production report Excel file",
    type=['xlsx'],
    help="Upload the Excel file generated by the production report tool"
)

# Initialize data variable
data = None
analytics_option = None

if uploaded_file is not None:
    try:
        # Read the Excel file
        excel_file = pd.ExcelFile(uploaded_file)
        
        # Get all sheet names (these are the style numbers)
        sheet_names = excel_file.sheet_names
        
        st.success(f"✅ File loaded successfully! Found {len(sheet_names)} style(s)")
        
        # Read all sheets into a combined dataframe
        all_data = []
        for sheet in sheet_names:
            df = pd.read_excel(uploaded_file, sheet_name=sheet)
            df['Style'] = sheet  # Add style column
            all_data.append(df)
        
        # Combine all data
        data = pd.concat(all_data, ignore_index=True)
        
        # Convert Date column to datetime
        data['Date'] = pd.to_datetime(data['Date'], format='%d/%b/%y', errors='coerce')
        
        # Remove rows with invalid dates
        data = data.dropna(subset=['Date'])
        
        # Sort by date
        data = data.sort_values('Date')
        
        st.markdown("---")
        
        # Sidebar for navigation
        st.sidebar.title("📊 Navigation")
        st.sidebar.markdown("---")
        st.sidebar.markdown("### Select Analytics View")
        analytics_option = st.sidebar.radio(
            "Choose visualization:",
            [
                "📊 Daily Actual Production Tracking",
                "📈 Cumulative Planned vs Actual",
                "📉 Daily Planned vs Actual",
                "🎯 Production Completion Percentage",
                "📅 Production Days Analysis"
            ],
            label_visibility="collapsed"
        )
        
    except Exception as e:
        st.error(f"❌ Error loading file: {str(e)}")
        data = None

# Main content area
if data is not None and analytics_option is not None:
    
    # Define process names and colors
    processes = ['Cutting', 'Sewing', 'Washing', 'Finishing', 'Packing']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
    
    # ========================================
    # OPTION 1: Daily Actual Production Tracking
    # ========================================
    if analytics_option == "📊 Daily Actual Production Tracking":
        st.markdown('<div class="main-header">📊 Daily Actual Production Tracking</div>', unsafe_allow_html=True)
        st.markdown('<div class="sub-header">Track actual production quantities across all processes</div>', unsafe_allow_html=True)
        st.markdown("---")
        
        # Filters
        st.markdown("### Filters")
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            selected_styles = st.multiselect(
                "Style",
                options=sorted(data['Style'].unique()),
                default=sorted(data['Style'].unique())
            )
        
        with col2:
            selected_pos = st.multiselect(
                "PO",
                options=sorted(data['PO'].unique()),
                default=sorted(data['PO'].unique())
            )
        
        with col3:
            selected_colours = st.multiselect(
                "Colour",
                options=sorted(data['Colour'].unique()),
                default=sorted(data['Colour'].unique())
            )
        
        with col4:
            date_range = st.date_input(
                "Date Range",
                value=(data['Date'].min(), data['Date'].max())
            )
        
        st.markdown("---")
        
        # Filter data
        filtered_data = data[
            (data['Style'].isin(selected_styles)) &
            (data['PO'].isin(selected_pos)) &
            (data['Colour'].isin(selected_colours)) &
            (data['Date'] >= pd.to_datetime(date_range[0])) &
            (data['Date'] <= pd.to_datetime(date_range[1]))
        ]
        
        if len(filtered_data) == 0:
            st.warning("⚠️ No data matches the selected filters")
        else:
            # Group by date and sum actual quantities
            daily_production = filtered_data.groupby('Date').agg({
                'Actual Cutting': 'sum',
                'Actual Sewing': 'sum',
                'Actual Washing': 'sum',
                'Actual Finishing': 'sum',
                'Actual Packing': 'sum'
            }).reset_index()
            
            # Create bar chart
            fig = go.Figure()
            
            for i, process in enumerate(processes):
                fig.add_trace(go.Bar(
                    x=daily_production['Date'],
                    y=daily_production[f'Actual {process}'],
                    name=process,
                    marker_color=colors[i]
                ))
            
            fig.update_layout(
                title="Daily Actual Production by Process",
                xaxis_title="Date",
                yaxis_title="Quantity",
                barmode='group',
                height=600,
                hovermode='x unified',
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )
            
            st.plotly_chart(fig, use_container_width=True)
    
    # ========================================
    # OPTION 2: Cumulative Planned vs Actual
    # ========================================
    elif analytics_option == "📈 Cumulative Planned vs Actual":
        st.markdown('<div class="main-header">📈 Cumulative Planned vs Actual Production</div>', unsafe_allow_html=True)
        st.markdown('<div class="sub-header">Compare cumulative planned and actual production over time (Style level)</div>', unsafe_allow_html=True)
        st.markdown("---")
        
        # Filters
        st.markdown("### Filters")
        col1, col2, col3 = st.columns(3)
        
        with col1:
            selected_style = st.selectbox(
                "Select Style",
                options=sorted(data['Style'].unique())
            )
        
        with col2:
            date_range = st.date_input(
                "Date Range",
                value=(data['Date'].min(), data['Date'].max()),
                key="cumulative_date"
            )
        
        with col3:
            view_mode = st.radio(
                "View Mode",
                options=["Daily", "Monthly"],
                horizontal=True
            )
        
        st.markdown("---")
        
        # Filter data
        filtered_data = data[
            (data['Style'] == selected_style) &
            (data['Date'] >= pd.to_datetime(date_range[0])) &
            (data['Date'] <= pd.to_datetime(date_range[1]))
        ]
        
        if len(filtered_data) == 0:
            st.warning("⚠️ No data matches the selected filters")
        else:
            if view_mode == "Daily":
                # Group by date and get max cumulative values
                cumulative_data = filtered_data.groupby('Date').agg({
                    'Cumulative Planned Cutting': 'max',
                    'Cumulative Actual Cutting': 'max',
                    'Cumulative Planned Sewing': 'max',
                    'Cumulative Actual Sewing': 'max',
                    'Cumulative Planned Washing': 'max',
                    'Cumulative Actual Washing': 'max',
                    'Cumulative Planned Finishing': 'max',
                    'Cumulative Actual Finishing': 'max',
                    'Cumulative Planned Packing': 'max',
                    'Cumulative Actual Packing': 'max'
                }).reset_index()
                
                # Create line charts for each process
                for process in processes:
                    fig = go.Figure()
                    
                    fig.add_trace(go.Scatter(
                        x=cumulative_data['Date'],
                        y=cumulative_data[f'Cumulative Planned {process}'],
                        mode='lines+markers',
                        name=f'Planned',
                        line=dict(dash='dash', width=3, color='#FF6B6B'),
                        marker=dict(size=6)
                    ))
                    
                    fig.add_trace(go.Scatter(
                        x=cumulative_data['Date'],
                        y=cumulative_data[f'Cumulative Actual {process}'],
                        mode='lines+markers',
                        name=f'Actual',
                        line=dict(width=3, color='#4ECDC4'),
                        marker=dict(size=6)
                    ))
                    
                    fig.update_layout(
                        title=f"{process} - Cumulative Planned vs Actual (Daily)",
                        xaxis_title="Date",
                        yaxis_title="Cumulative Quantity",
                        height=450,
                        hovermode='x unified',
                        legend=dict(
                            orientation="h",
                            yanchor="bottom",
                            y=1.02,
                            xanchor="right",
                            x=1
                        )
                    )
                    
                    st.plotly_chart(fig, use_container_width=True)
            
            else:  # Monthly view
                # Add year-month column for grouping
                filtered_data['YearMonth'] = filtered_data['Date'].dt.to_period('M')
                
                # Get the last day of each month to get the cumulative values
                monthly_data = filtered_data.groupby('YearMonth').last().reset_index()
                
                # Convert YearMonth back to string for display
                monthly_data['MonthLabel'] = monthly_data['YearMonth'].astype(str)
                
                # Create bar charts for each process
                for process in processes:
                    fig = go.Figure()
                    
                    # Add planned bars
                    fig.add_trace(go.Bar(
                        x=monthly_data['MonthLabel'],
                        y=monthly_data[f'Cumulative Planned {process}'],
                        name='Planned',
                        marker_color='#FF6B6B',
                        text=monthly_data[f'Cumulative Planned {process}'],
                        textposition='outside'
                    ))
                    
                    # Add actual bars
                    fig.add_trace(go.Bar(
                        x=monthly_data['MonthLabel'],
                        y=monthly_data[f'Cumulative Actual {process}'],
                        name='Actual',
                        marker_color='#4ECDC4',
                        text=monthly_data[f'Cumulative Actual {process}'],
                        textposition='outside'
                    ))
                    
                    fig.update_layout(
                        title=f"{process} - Cumulative Planned vs Actual (Monthly)",
                        xaxis_title="Month",
                        yaxis_title="Cumulative Quantity",
                        height=450,
                        barmode='group',
                        hovermode='x unified',
                        legend=dict(
                            orientation="h",
                            yanchor="bottom",
                            y=1.02,
                            xanchor="right",
                            x=1
                        )
                    )
                    
                    st.plotly_chart(fig, use_container_width=True)
    
    # ========================================
    # OPTION 3: Daily Planned vs Actual
    # ========================================
    elif analytics_option == "📉 Daily Planned vs Actual":
        st.markdown('<div class="main-header">📉 Daily Planned vs Actual Production</div>', unsafe_allow_html=True)
        st.markdown('<div class="sub-header">Compare daily planned and actual production (with PO/Colour level filtering)</div>', unsafe_allow_html=True)
        st.markdown("---")
        
        # Filters
        st.markdown("### Filters")
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            selected_styles = st.multiselect(
                "Style",
                options=sorted(data['Style'].unique()),
                default=[sorted(data['Style'].unique())[0]],
                key="daily_plan_style"
            )
        
        with col2:
            selected_pos = st.multiselect(
                "PO",
                options=sorted(data['PO'].unique()),
                default=sorted(data['PO'].unique()),
                key="daily_plan_po"
            )
        
        with col3:
            selected_colours = st.multiselect(
                "Colour",
                options=sorted(data['Colour'].unique()),
                default=sorted(data['Colour'].unique()),
                key="daily_plan_colour"
            )
        
        with col4:
            date_range = st.date_input(
                "Date Range",
                value=(data['Date'].min(), data['Date'].max()),
                key="daily_plan_date"
            )
        
        st.markdown("---")
        
        # Filter data
        filtered_data = data[
            (data['Style'].isin(selected_styles)) &
            (data['PO'].isin(selected_pos)) &
            (data['Colour'].isin(selected_colours)) &
            (data['Date'] >= pd.to_datetime(date_range[0])) &
            (data['Date'] <= pd.to_datetime(date_range[1]))
        ]
        
        if len(filtered_data) == 0:
            st.warning("⚠️ No data matches the selected filters")
        else:
            # Group by date and sum quantities
            daily_data = filtered_data.groupby('Date').agg({
                'Planned Cutting': 'sum',
                'Actual Cutting': 'sum',
                'Planned Sewing': 'sum',
                'Actual Sewing': 'sum',
                'Planned Washing': 'sum',
                'Actual Washing': 'sum',
                'Planned Finishing': 'sum',
                'Actual Finishing': 'sum',
                'Planned Packing': 'sum',
                'Actual Packing': 'sum'
            }).reset_index()
            
            # Create charts for each process
            for process in processes:
                fig = go.Figure()
                
                fig.add_trace(go.Scatter(
                    x=daily_data['Date'],
                    y=daily_data[f'Planned {process}'],
                    mode='lines+markers',
                    name=f'Planned',
                    line=dict(dash='dash', width=3, color='#FF6B6B'),
                    marker=dict(size=6)
                ))
                
                fig.add_trace(go.Scatter(
                    x=daily_data['Date'],
                    y=daily_data[f'Actual {process}'],
                    mode='lines+markers',
                    name=f'Actual',
                    line=dict(width=3, color='#4ECDC4'),
                    marker=dict(size=6)
                ))
                
                fig.update_layout(
                    title=f"{process} - Daily Planned vs Actual",
                    xaxis_title="Date",
                    yaxis_title="Daily Quantity",
                    height=450,
                    hovermode='x unified',
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )
                
                st.plotly_chart(fig, use_container_width=True)
    
    # ========================================
    # OPTION 4: Production Completion Percentage
    # ========================================
    elif analytics_option == "🎯 Production Completion Percentage":
        st.markdown('<div class="main-header">🎯 Production Completion Percentage</div>', unsafe_allow_html=True)
        st.markdown('<div class="sub-header">View completion percentage for each process (based on latest cumulative data)</div>', unsafe_allow_html=True)
        st.markdown("---")
        
        # Filter
        st.markdown("### Filter")
        selected_style = st.selectbox(
            "Select Style",
            options=sorted(data['Style'].unique()),
            key="progress_style"
        )
        
        st.markdown("---")
        
        # Filter data for selected style
        style_data = data[data['Style'] == selected_style]
        
        # Get the last row (most recent date) for cumulative values
        last_row = style_data.sort_values('Date').iloc[-1]
        
        # Extract cumulative planned and actual values
        progress_data = []
        for process in processes:
            planned = last_row[f'Cumulative Planned {process}']
            actual = last_row[f'Cumulative Actual {process}']
            
            # Calculate percentage
            if planned > 0:
                percentage = (actual / planned) * 100
            else:
                percentage = 0
            
            progress_data.append({
                'Process': process,
                'Planned': int(planned),
                'Actual': int(actual),
                'Remaining': int(max(0, planned - actual)),
                'Percentage': round(percentage, 1)
            })
        
        progress_df = pd.DataFrame(progress_data)
        
        # Display as a styled table
        st.markdown(f"### Progress Summary for Style: **{selected_style}**")
        st.markdown(f"*As of {last_row['Date'].strftime('%d %B %Y')}*")
        st.markdown("")
        
        # Create a more detailed table with styling
        styled_df = progress_df[['Process', 'Actual', 'Planned', 'Remaining', 'Percentage']].copy()
        styled_df['Percentage'] = styled_df['Percentage'].apply(lambda x: f"{x}%")
        
        # Display the table with custom styling
        st.dataframe(
            styled_df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Process": st.column_config.TextColumn("Process", width="medium"),
                "Actual": st.column_config.NumberColumn("Actual", width="small", format="%d"),
                "Planned": st.column_config.NumberColumn("Planned", width="small", format="%d"),
                "Remaining": st.column_config.NumberColumn("Remaining", width="small", format="%d"),
                "Percentage": st.column_config.TextColumn("Completion %", width="small")
            }
        )
    
    # ========================================
    # OPTION 5: Production Days Analysis
    # ========================================
    elif analytics_option == "📅 Production Days Analysis":
        st.markdown('<div class="main-header">📅 Production Days Analysis</div>', unsafe_allow_html=True)
        st.markdown('<div class="sub-header">Track production days vs non-production days per month (excluding Sundays)</div>', unsafe_allow_html=True)
        st.markdown("---")
        
        # Get the date range from the data
        min_date = data['Date'].min()
        max_date = data['Date'].max()
        
        # Get all unique dates where production happened
        production_dates = set(data['Date'].dt.date)
        
        # Create a complete date range
        all_dates = pd.date_range(start=min_date, end=max_date, freq='D')
        
        # Analyze by month
        monthly_analysis = []
        
        for year_month in pd.period_range(start=min_date, end=max_date, freq='M'):
            # Get all dates in this month
            month_start = year_month.to_timestamp()
            month_end = (year_month + 1).to_timestamp() - pd.Timedelta(days=1)
            
            # Get all dates in the month
            month_dates = pd.date_range(start=month_start, end=month_end, freq='D')
            
            # Count working days (exclude Sundays)
            working_days = [d for d in month_dates if d.dayofweek != 6]  # 6 = Sunday
            total_working_days = len(working_days)
            
            # Count production days (exclude Sundays)
            production_days_count = sum(1 for d in working_days if d.date() in production_dates)
            
            # Count non-production days
            non_production_days_count = total_working_days - production_days_count
            
            monthly_analysis.append({
                'Month': year_month.strftime('%b %Y'),
                'Total Working Days': total_working_days,
                'Production Days': production_days_count,
                'Non-Production Days': non_production_days_count,
                'Production Rate': f"{(production_days_count / total_working_days * 100):.1f}%" if total_working_days > 0 else "0%"
            })
        
        # Create dataframe
        analysis_df = pd.DataFrame(monthly_analysis)
        
        # Display summary table
        st.markdown("### Monthly Production Days Summary")
        st.markdown("*Sundays are excluded from the analysis*")
        st.markdown("")
        
        st.dataframe(
            analysis_df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Month": st.column_config.TextColumn("Month", width="medium"),
                "Total Working Days": st.column_config.NumberColumn("Total Working Days", width="small", format="%d"),
                "Production Days": st.column_config.NumberColumn("Production Days", width="small", format="%d"),
                "Non-Production Days": st.column_config.NumberColumn("Non-Production Days", width="small", format="%d"),
                "Production Rate": st.column_config.TextColumn("Production Rate", width="small")
            }
        )
        
        st.markdown("---")
        
        # Create bar chart
        fig = go.Figure()
        
        fig.add_trace(go.Bar(
            x=analysis_df['Month'],
            y=analysis_df['Production Days'],
            name='Production Days',
            marker_color='#4ECDC4',
            text=analysis_df['Production Days'],
            textposition='inside'
        ))
        
        fig.add_trace(go.Bar(
            x=analysis_df['Month'],
            y=analysis_df['Non-Production Days'],
            name='Non-Production Days',
            marker_color='#FF6B6B',
            text=analysis_df['Non-Production Days'],
            textposition='inside'
        ))
        
        fig.update_layout(
            title="Production Days vs Non-Production Days by Month",
            xaxis_title="Month",
            yaxis_title="Number of Days",
            barmode='stack',
            height=500,
            hovermode='x unified',
            legend=dict(
                orientation="h",
                yanchor="bottom",
                y=1.02,
                xanchor="right",
                x=1
            )
        )
        
        st.plotly_chart(fig, use_container_width=True)
        
        st.markdown("---")
        
        # Create production rate line chart
        fig2 = go.Figure()
        
        # Extract numeric production rate
        production_rate_numeric = [float(rate.strip('%')) for rate in analysis_df['Production Rate']]
        
        fig2.add_trace(go.Scatter(
            x=analysis_df['Month'],
            y=production_rate_numeric,
            mode='lines+markers',
            name='Production Rate',
            line=dict(width=3, color='#2ca02c'),
            marker=dict(size=10),
            text=[f"{rate}%" for rate in production_rate_numeric],
            textposition='top center'
        ))
        
        fig2.update_layout(
            title="Production Rate Trend by Month",
            xaxis_title="Month",
            yaxis_title="Production Rate (%)",
            height=400,
            hovermode='x unified',
            yaxis=dict(range=[0, 100])
        )
        
        st.plotly_chart(fig2, use_container_width=True)

else:
    # Show available analytics when no file is uploaded
    st.markdown("### Available Analytics:")
    st.markdown("""
    - **📊 Daily Actual Production Tracking** - Bar chart showing actual production by process
    - **📈 Cumulative Planned vs Actual** - Line/Bar charts comparing cumulative targets vs reality (Daily/Monthly views)
    - **📉 Daily Planned vs Actual** - Line charts for day-to-day comparison
    - **🎯 Production Completion Percentage** - Table showing completion percentage for each process
    - **📅 Production Days Analysis** - Track production days vs non-production days per month
    """)

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #666; font-size: 0.9rem;'>
    <p>Production Analytics Dashboard v2.1</p>
</div>
""", unsafe_allow_html=True)
